version: "3"

services:
  web:
    image: metfan1981/jenkins-image:${BUILD_ID}
    ports:
      - "8080:80"
    env_file:
      - "env"
    networks:
      - front-net
    volumes: 
      - jenkins_${BUILD_ID}:/var/www/html

networks:
  front-net:

volumes:
  jenkins_${BUILD_ID}:
