version: "3"

services:
  jenkins:
    container_name: jenkins_w_ansible
    image: ansible-jenkins
    ports: 
      - "8080:8080"
    volumes:
      - jenkins_w_ansible:/var/jenkins_home
    networks:
      - net

networks:
  net:
